package trabajo_final.poo.burako.modelo;

public enum Evento {
    SELECCIONARMODOJ,RESPUESTAINCORRECTA,INGRESARJUGADOR,INGRESAREQUIPO, INGRESARJUGCONEQUI, INICIOPARTIDA, JUGADORCORTO, INICIARTURNO, TOMARFICHA, TOMAROTRA, MSJTOMEOTRA, MSJSEHANTOMADO,
    MSJNOSEPUEDEDEPOSITAR, MSJCOMPROMUERTO, SALTOLINEA, MENUTIPOJUGADA, MSJJUGADAINV1, MSJYASEHANTOMADO, MSJPILAVACIA, MENUSELECCIONF, MSJDEBESELECCIONARF, MENUDEPOSITARF, MSJJUGADAINV2, MSJSEHABAJADO,
    MSJNOPUEDECORTAR, MSJPOSINGRESADA1, MSJPOSINGRESADA2, JUEGONUMERADO1, MSJPOSINGRESADA3, MSJJUGADAINV3, MSJSEHACOMPLETADO, JUEGOS1, JUEGOS2, JUEGONUMERADO2, MSJJUGADAINV4, MSJJUGADAINV5,
    MSJNOCOMNIINT, MSJSEINTERCAMBIARON;
}
